version: "3.7"
services:
  web: 
    image: nginx:1.16.1
    ports: 
      - "80:80"
    volumes:
      - "./example.nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./frontend:/var/www/html:ro"
  webservice:
    # replace username/repo:tag with your name and image details
    #image: 
    # build: ./server
    build: 
      dockerfile: ./server/Dockerfile
      context: ./servers
      target: dev
      # args:
      #   MICROSCANNER_TOKEN: 
    volumes:
      - "./server:/app"
    ports:
      - "3000:3000"
    # env_file: 
    #   - ./server/.env.development
    networks:
      - webnet
networks:
  webnet: