version: "3.7"
services:
  web: 
    image: nginx:1.16.1
    ports: 
      - "81:80"
    volumes:
      - "./example.nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./frontend:/var/www/html:ro"
    labels:
      traefik.http.routers.http-1.rule: Host(`http-1.localhost`)
  webservice:
    # replace username/repo:tag with your name and image details
    #image: 
    # build: ./server
    build: 
      dockerfile: Dockerfile
      context: ./server
      # target: development
      target: production
      args:
        MICROSCANNER_TOKEN: MjIzMTU3ZWQ0NzQy
    volumes:
      - "./server:/app"
    ports:
      - "3000:3000"
    # env_file: 
    #   - ./server/.env.development
    networks:
      - webnet
  traefik:
    image: traefik:v2.0.4
    command: 
      - --log.level=INFO
      - --providers.docker
      - --api.insecure=true
      - --entrypoints.web.address=:80
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"
networks:
  webnet: